### ISSUE TITLE
Installation of pySerial or pyVisa required

### ISSUE THREAD

**Issue by msb002** [AlexShkarin/pyLabLib-v0#2]
I ran into a bug where initializing a FW102 (thorlabs) would produce an error. It took some work to discover it was caused by the missing package pyserial. I think adding this to the requirements in setup could resolve this.

**Comment by AlexShkarin** [comment]
Thank you for pointing it out!

I originally decided to not include these libraries into the default dependencies, since I envisioned the library to be more universal (for data analysis as well as device communication / automation). Hence, I didn't want to add lots of specific device-related dependencies. I agree, now that the focus shifted, it should be included by default, or at least the error message should be more explicit. I'll fix it in the next release.

For now, there's an option to specify device dependencies when installing from pip as ``pip install pylablib[devio]`` (instead of the usual ``pip install pylablib``), which should grab the additional packages.
